### ISSUE TITLE
Customize the Merge Commit Message in the Release Note

### ISSUE THREAD

**Issue by na-ga** [pipe-cd/actions-gh-release#22]
In our team, there are many commits in a single Release, so the Release Note uses the `releaseNoteGenerator.commitInclude.prefix` option to output only the `Merge pull request #`. 

The option `releaseNoteGenerator.showCommitter` is enabled, the Committer Name for Merge Commit will be Github, so Release Note will show the following.

```
- Merge pull request #NUMBER from ORG/BRANCH HASH - by GitHub
```

I think this message is difficult to understand. so I would like to customize the Merge Commit Message as follows.

```
- #NUMBER PR_TITLE from ORG/BRANCH HASH - by @PR_OWNER
```

In order to do this, we need to call the Github API. This issue is related to what we discussed earlier at https://github.com/pipe-cd/actions-gh-release/issues/7. We want to discuss whether these implementations are feasible, as they create a dependency with the Github API.

**Comment by knanao** [comment]
Thank you for your suggestion.
/close
